### ISSUE TITLE
Soldity compiler version

### ISSUE THREAD

**Issue by Qunal** [PatrickAlphaC/erc20-brownie-py#2]
OpenZepplin needs less then 0.8
```
// contracts/OurToken.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

ParserError: Source file requires different compiler version (current compiler is 0.8.11+commit.d7f03943.Linux.g++) - note that nightly builds are considered to be strictly less than the released version
 --> /root/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.4.0/contracts/token/ERC20/ERC20.sol:3:1:
  |
```
**3 | pragma solidity >=0.6.0 <0.8.0;**

yaml settings
```

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
```
This is win 10 wsl installation with ubuntu
